apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort:
    {{ if Values.service.targetPort }}
      {{ .Values.service.port }}
    {{ end }}
    {{ if not Values.service.targetPort }}
      {{ .Values.service.targetPort }}
    {{ end }}
  selector:
    app: techtrends
  type: {{ .Values.service.type }}