## provide the name of the namespace
namespace:
  name: sandbox

service:
  port: 4111
  protocol: TCP
  targetPort: 3111
  type: ClusterIP

## define the image to execute with the Deployment
image:
  repository: techtrends
  tag: latest
  imagePullPolicy: IfNotPresent

## set the number of replicas for an application
replicaCount: 1

resources:
  requests:
    cpu: "250m"
    memory: "64Mi"
  limits:
    cpu: "500m"
    memory: "128Mi"

containerPort: 3111

livenessProbe:
  path: /healthz
readinessProbe:
  path: /healthz

